### ISSUE TITLE
 Thesis Meeting | Oct 8, 2024 - 2:30pm - *Teams*

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#102]
Unfortunately, I'm still sick so this meeting will also have to be virtual. Honestly, if I lived closer to Hamilton I think in-person meetings would be beneficial, but they tend to essentially use up my whole day with travel time, prep, figuring out meals, and the mental effort for traffic, etc. Is it reasonable to make virtual meetings the norm? I'll come in for my seminar/defense as well as anything that specifically comes up!

# Important Items

1. Paper Review! See #103 
   1. 3/3 rejections, mainly based on the subjectivity we were already aware of 😔
   2. Honestly not sure how possible it will be to address these concerns while staying in the page _and_ time limits (Oct 10!)
3. Next steps to focus on?
   1. Go through IEEE 29119 family of standards
   2. Automate category discrepancies from glossary
   4. Start "formalizing" of generated graphs using [`graph_tool`](https://graph-tool.skewed.de/static/doc/quickstart.html#quickstart)
4. Degree reqs timeline: is our Oct timeline still reasonable? If not, that's fine by me, but what does that look like as far as coordinating with Drs. Nedialkov and Paige?

# Review Items

1. Review of Introduction section #96 - any updates/initial notes?
2. Reclassification of discrepancies #97: Chapter 5 of my [thesis](https://github.com/samm82/TestGen-Thesis/blob/129c65b03818f6413aedf6c6288d5d465371229c/thesis.pdf) and Section IV of my [paper](https://github.com/samm82/TestGen-Thesis/blob/129c65b03818f6413aedf6c6288d5d465371229c/paper.pdf)
   1. Reclassifying based on "syntax" done in #101!

**Comment by smiths** [comment]
@samm82 a virtual meeting is fine and being virtual by default is fine.  If needed, especially if we are having a longer meeting to justify the travel time, we might request an in-person meeting in the future.

**Comment by JacquesCarette** [comment]
Safest for me to explicitly agree here.

**Comment by samm82** [comment]
Finally got around to formalizing my notes from this meeting! 😅 Currently, my defense will likely be in early November

# TODO
- [ ] Articulate a "pure" motivation: instead of focusing on the consequences of unstandardization, just "require" the same standard of documents as our artifacts (e.g., code).
- [ ] Examples of "violations" in the intro should be stronger and up front
- [ ] Populate the Declaration of Achievement section
- [ ] `nameref` leads to traceability that is too passive; instead, say "defined in Section _"
   - [ ] backward links are preferred; if needed earlier, a more abstract definition can be introduced
      - the reader shouldn't NEED to jump around to understand information
      - excerpts of knowledge can be given to give an impression, but explaining every detail doesn't need to be outlined at the onset; e.g., "(to be outlined later)" can be used
- [ ] Formalize definitions used for data collection/analysis (e.g., using data structures for graphs; a source has a set of terms each with a definition and a possibly empty set of parents…)

# Next Steps:
- [ ] I should work on slides for my seminar in downtime during review
- [ ] I should NOT go through any new sources 😢
- [ ] Consider future work
   - [ ] How would I fix the issues in #103 in the absence of page/time limits?
   - [ ] Other things I didn't have time for, such as more automated analysis, other documents, etc.
