### ISSUE TITLE
Thesis Meeting | July 15, 2024 - 10:30am - ITB 167

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#67]
1. Take a look at my generated graphs (see [assets/graphs](https://github.com/samm82/TestGen-Thesis/tree/main/assets/graphs)) and discuss areas to analyze/discuss (and/or how to make these graphs more useful).
   1. Should the generated `*.tex` files be under version control? I think this would make the `diff`s more meaningful (i.e., seeing how a change to the code changes the generated output), but don't want to "clutter up" the commits more than I already do!
   2. Does my legend make sense? Any feedback on it? (I'll hopefully 🤞 be making some improvements tonight before tomorrow morning!)
2. Start discussing what our analysis will look like: "identify the principles for our new classification and the scope" to uncover the "rationale" that we will apply (see #65).

**Comment by smiths** [comment]
I'm looking forward to our meeting.  The graph I looked at was incredibly dense with information!  During our meeting you'll have to tell me how you built the graphs and what information is in the arrows.

**Comment by samm82** [comment]
1. We looked at the graphs! 😁 "Standards-only" versions may be helpful, as well as the option to color arrows based on their source. This could entail either having an arrow for each type of source or only the most "rigid" one, and my thoughts on grouping them would be standards (IEEE, ISO/IEC, potentially blue), collections/commentary on standards (SWEBOK, ISTQB, Firesmith, potentially black), and other (potentially red). Adding arrows likely only makes sense for specific graphs (e.g., the subsets of them, like the recovery graph).
   1. `*.tex` files can be added to version control. It's my repo, so since it would be helpful for me, I should add them! 😁
   2. My legend mostly makes sense. I should explain what I mean by the different relations, including why I include synonyms (or, more generally, why their existence isn't intrinsically a problem; e.g., white-/black-box testing).
2. Analyzing these graphs should include identifying "problem points". We came up with the first two, and I've been thinking of others:
   - Two nodes with both a child-parent _and_ synonym relation
   - A node that is a synonym of _different_ terms
   - Cycles of child-parent relations (including self-cycles)
   More generally, analysis will likely be most fruitful when looking at smaller subset of these graphs, and "massaging" them to be more coherent/consistent.

# TODO
_These may be pulled out into other issues but are grouped here for now for simplicity_
- [ ] Add coloring to edges based on most rigid source
- [ ] Add option to add edges for different sources (including rigidity) - will be done for recovery to start
- [ ] Add `*.tex` files to version control
- [ ] Explain meaning of child-parent relations (in body; link to within figure captions): children are refinements, subsets, more concrete, and/or lower-level
- [ ] Explain rationale behind implied relations/terms
- [ ] Explain why synonyms aren't intrinsically bad (including when they are)
- [ ] Track problem points
   - [ ] Document what they are
   - [ ] Output list of them when generating graphs
- [ ] **Not discussed in meeting:** Introduce recommendations section
   - @smiths Would it be better to have separate "problems" and "recommendations" sections, or to describe the "problems" alongside their "recommendations"? I think the latter makes the most sense, but people may just want to see the problems to make their own conclusions. Any ideas on a good compromise between "cohesion" and "coupling"?
- [ ] Explain rationale for recommendations for recovery testing terms

**Comment by smiths** [comment]
Great summary @samm82.  I actually like problems to be separate from the solutions.  You will have more content on problems than solutions, so intermixing them will likely feel unbalanced.  I think you have a good chunk of your contribution just pointing out problems.  This part of your Masters will be fairly non-controversial.  This will be something that others could potentially use as a jumping off point to present their own solutions.  You can be one of the people that jumps off from the problems to a solution, but it will be cleanest if you present the solution separate from the problem.

I know you already have a long to do list, but starting a draft of your paper would be a good addition to the list.  :smile:

**Comment by samm82** [comment]
Just finished the first iteration of implementing colors! 🥳 I decided to color standards green, commentaries/collections blue, textbooks maroon, and others black. I also have it so that the most "rigid" information is displayed, with an example below. Is there anything in particular you think would be useful to have in the short-term? @smiths (If our discussion is coherent enough, feel free to chime in as well @JacquesCarette! 😁) If not, I think I'll pivot away from graph-generating for the next little bit. I'll pull the other action items (along with whatever we decide in regards to coloring) to separate issues to tackle, and then this issue can be closed!

For example, there are two arrows going from Volume to Capacity Testing. This communicates that this relation is given by a commentary/collection, but implied by a standard (which is a "stronger" source). If it was reversed (i.e., explicit in a standard), then there would only be a green arrow. The fact that it was implied by a "weaker" source doesn't add that much information. Of course, this could be configurable in the future, but I think this is a good first step! (What I thought would be easy was hard, and what I thought would be hard was easy 🙃 I love software development.)

![dual arrows](https://github.com/user-attachments/assets/920c341e-b0c2-447e-a7ae-2c5f55230392)

**Comment by smiths** [comment]
@samm82 what do you mean by rigid?  I thought rigid meant not including the implicit arrows, but your screenshot shows the dashed arrow.

I agree that you don't need to do more with the graphs now.  Your graphs already can tell a story.  We can use them in the ICSE paper.  I think you should prioritize writing at this time.

**Comment by samm82** [comment]
You're right that I overloaded the term "rigid"; I guess what I really meant was "strongest" (i.e., "from the most credible source", based on my ordering of them).

**Comment by samm82** [comment]
Finally migrated the last remaining TODO to an issue, so this can be closed! 😅
