### ISSUE TITLE
Document rationale for relations between approaches

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#69]
These should be done in the body of the thesis, with a link to within figure captions

# TODO

- [ ] Meaning of child-parent relations: children are refinements, subsets, more concrete, and/or lower-level
- [ ] Implied relations/terms
   - [ ] Criteria for entry into spreadsheet
   - [ ] Criteria for inclusion in graphs

**Comment by smiths** [comment]
Great!
